// Generated by cdk-import
import * as cdk from '@aws-cdk/core';

/**
 * A resource provider for Aqua Enterprise KubeEnforcer.
 *
 * @schema CfnKubeenforcerProps
 */
export interface CfnKubeenforcerProps {
  /**
   * EKS cluster name
   *
   * @schema CfnKubeenforcerProps#ClusterID
   */
  readonly clusterId?: string;

  /**
   * Secrets Manager ARN for kubeconfig file
   *
   * @schema CfnKubeenforcerProps#KubeConfig
   */
  readonly kubeConfig?: string;

  /**
   * IAM to use with EKS cluster authentication, if not resource execution role will be used
   *
   * @schema CfnKubeenforcerProps#RoleArn
   */
  readonly roleArn?: string;

  /**
   * Namespace to use with helm. Created if doesn't exist and default will be used if not provided
   *
   * @schema CfnKubeenforcerProps#Namespace
   */
  readonly namespace?: string;

  /**
   * Name for the helm release
   *
   * @schema CfnKubeenforcerProps#Name
   */
  readonly name?: string;

  /**
   * Custom Values can optionally be specified
   *
   * @schema CfnKubeenforcerProps#Values
   */
  readonly values?: any;

  /**
   * String representation of a values.yaml file
   *
   * @schema CfnKubeenforcerProps#ValueYaml
   */
  readonly valueYaml?: string;

  /**
   * Version can be specified, if not latest will be used
   *
   * @schema CfnKubeenforcerProps#Version
   */
  readonly version?: string;

  /**
   * Custom Value Yaml file can optionally be specified
   *
   * @schema CfnKubeenforcerProps#ValueOverrideURL
   */
  readonly valueOverrideUrl?: string;

  /**
   * Timeout for resource provider. Default 60 mins
   *
   * @schema CfnKubeenforcerProps#TimeOut
   */
  readonly timeOut?: number;

  /**
   * For network connectivity to Cluster inside VPC
   *
   * @schema CfnKubeenforcerProps#VPCConfiguration
   */
  readonly vpcConfiguration?: CfnKubeenforcerPropsVpcConfiguration;

}

/**
 * Converts an object of type 'CfnKubeenforcerProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnKubeenforcerProps(obj: CfnKubeenforcerProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ClusterID': obj.clusterId,
    'KubeConfig': obj.kubeConfig,
    'RoleArn': obj.roleArn,
    'Namespace': obj.namespace,
    'Name': obj.name,
    'Values': obj.values,
    'ValueYaml': obj.valueYaml,
    'Version': obj.version,
    'ValueOverrideURL': obj.valueOverrideUrl,
    'TimeOut': obj.timeOut,
    'VPCConfiguration': toJson_CfnKubeenforcerPropsVpcConfiguration(obj.vpcConfiguration),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * For network connectivity to Cluster inside VPC
 *
 * @schema CfnKubeenforcerPropsVpcConfiguration
 */
export interface CfnKubeenforcerPropsVpcConfiguration {
  /**
   * Specify one or more security groups
   *
   * @schema CfnKubeenforcerPropsVpcConfiguration#SecurityGroupIds
   */
  readonly securityGroupIds?: string[];

  /**
   * Specify one or more subnets
   *
   * @schema CfnKubeenforcerPropsVpcConfiguration#SubnetIds
   */
  readonly subnetIds?: string[];

}

/**
 * Converts an object of type 'CfnKubeenforcerPropsVpcConfiguration' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnKubeenforcerPropsVpcConfiguration(obj: CfnKubeenforcerPropsVpcConfiguration | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'SecurityGroupIds': obj.securityGroupIds?.map(y => y),
    'SubnetIds': obj.subnetIds?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 * A CloudFormation `Aqua::Enterprise::KubeEnforcer`
 *
 * @cloudformationResource Aqua::Enterprise::KubeEnforcer
 * @stability external
 * @link https://github.com/aquasecurity/aqua-helm.git
 */
export class CfnKubeenforcer extends cdk.CfnResource {
  /**
  * The CloudFormation resource type name for this resource class.
  */
  public static readonly CFN_RESOURCE_TYPE_NAME = "Aqua::Enterprise::KubeEnforcer";

  /**
   * Resource props.
   */
  public readonly props: CfnKubeenforcerProps;

  /**
   * Attribute `Aqua::Enterprise::KubeEnforcer.ID`
   * @link https://github.com/aquasecurity/aqua-helm.git
   */
  public readonly attrId: string;

  /**
   * Create a new `Aqua::Enterprise::KubeEnforcer`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: cdk.Construct, id: string, props: CfnKubeenforcerProps) {
    super(scope, id, { type: CfnKubeenforcer.CFN_RESOURCE_TYPE_NAME, properties: toJson_CfnKubeenforcerProps(props)! });

    this.props = props;

    this.attrId = cdk.Token.asString(this.getAtt('ID'));
  }
}