// Generated by cdk-import
import * as cdk from '@aws-cdk/core';

/**
 * This resource allows to create, read, update and delete a network peering
 *
 * @schema CfnNetworkpeeringProps
 */
export interface CfnNetworkpeeringProps {
  /**
   * The unique identifier of the project.
   *
   * @schema CfnNetworkpeeringProps#ProjectId
   */
  readonly projectId: string;

  /**
   * Unique identifier of the Atlas VPC container for the AWS region.
   *
   * @schema CfnNetworkpeeringProps#ContainerId
   */
  readonly containerId?: string;

  /**
   * AWS region where the peer VPC resides. Returns null if the region is the same region in which the Atlas VPC resides.
   *
   * @schema CfnNetworkpeeringProps#AccepterRegionName
   */
  readonly accepterRegionName?: string;

  /**
   * AWS account ID of the owner of the peer VPC.
   *
   * @schema CfnNetworkpeeringProps#AwsAccountId
   */
  readonly awsAccountId?: string;

  /**
   * The name of the provider
   *
   * @schema CfnNetworkpeeringProps#ProviderName
   */
  readonly providerName?: string;

  /**
   * Peer VPC CIDR block or subnet.
   *
   * @schema CfnNetworkpeeringProps#RouteTableCIDRBlock
   */
  readonly routeTableCidrBlock?: string;

  /**
   * Unique identifier of the peer VPC.
   *
   * @schema CfnNetworkpeeringProps#VpcId
   */
  readonly vpcId: string;

  /**
   * Unique identifier for the peering connection.
   *
   * @schema CfnNetworkpeeringProps#ConnectionId
   */
  readonly connectionId?: string;

  /**
   * @schema CfnNetworkpeeringProps#ApiKeys
   */
  readonly apiKeys: ApiKeyDefinition;

}

/**
 * Converts an object of type 'CfnNetworkpeeringProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnNetworkpeeringProps(obj: CfnNetworkpeeringProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ProjectId': obj.projectId,
    'ContainerId': obj.containerId,
    'AccepterRegionName': obj.accepterRegionName,
    'AwsAccountId': obj.awsAccountId,
    'ProviderName': obj.providerName,
    'RouteTableCIDRBlock': obj.routeTableCidrBlock,
    'VpcId': obj.vpcId,
    'ConnectionId': obj.connectionId,
    'ApiKeys': toJson_ApiKeyDefinition(obj.apiKeys),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema apiKeyDefinition
 */
export interface ApiKeyDefinition {
  /**
   * @schema apiKeyDefinition#PublicKey
   */
  readonly publicKey?: string;

  /**
   * @schema apiKeyDefinition#PrivateKey
   */
  readonly privateKey?: string;

}

/**
 * Converts an object of type 'ApiKeyDefinition' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ApiKeyDefinition(obj: ApiKeyDefinition | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'PublicKey': obj.publicKey,
    'PrivateKey': obj.privateKey,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 * A CloudFormation `MongoDB::Atlas::NetworkPeering`
 *
 * @cloudformationResource MongoDB::Atlas::NetworkPeering
 * @stability external
 * @link http://unknown-url
 */
export class CfnNetworkpeering extends cdk.CfnResource {
  /**
  * The CloudFormation resource type name for this resource class.
  */
  public static readonly CFN_RESOURCE_TYPE_NAME = "MongoDB::Atlas::NetworkPeering";

  /**
   * `MongoDB::Atlas::NetworkPeering.ProjectId`
   * The unique identifier of the project.
   * @link http://unknown-url
   */
  public readonly projectId: string;
  /**
   * `MongoDB::Atlas::NetworkPeering.ContainerId`
   * Unique identifier of the Atlas VPC container for the AWS region.
   * @link http://unknown-url
   */
  public readonly containerId: string | undefined;
  /**
   * `MongoDB::Atlas::NetworkPeering.AccepterRegionName`
   * AWS region where the peer VPC resides. Returns null if the region is the same region in which the Atlas VPC resides.
   * @link http://unknown-url
   */
  public readonly accepterRegionName: string | undefined;
  /**
   * `MongoDB::Atlas::NetworkPeering.AwsAccountId`
   * AWS account ID of the owner of the peer VPC.
   * @link http://unknown-url
   */
  public readonly awsAccountId: string | undefined;
  /**
   * `MongoDB::Atlas::NetworkPeering.ProviderName`
   * The name of the provider
   * @link http://unknown-url
   */
  public readonly providerName: string | undefined;
  /**
   * `MongoDB::Atlas::NetworkPeering.RouteTableCIDRBlock`
   * Peer VPC CIDR block or subnet.
   * @link http://unknown-url
   */
  public readonly routeTableCIDRBlock: string | undefined;
  /**
   * `MongoDB::Atlas::NetworkPeering.VpcId`
   * Unique identifier of the peer VPC.
   * @link http://unknown-url
   */
  public readonly vpcId: string;
  /**
   * `MongoDB::Atlas::NetworkPeering.ConnectionId`
   * Unique identifier for the peering connection.
   * @link http://unknown-url
   */
  public readonly connectionId: string | undefined;
  /**
   * `MongoDB::Atlas::NetworkPeering.ApiKeys`
   * @link http://unknown-url
   */
  public readonly apiKeys: apiKeyDefinition;
  /**
   * Attribute `MongoDB::Atlas::NetworkPeering.Id`
   * @link http://unknown-url
   */
  public readonly attrId: string;
  /**
   * Attribute `MongoDB::Atlas::NetworkPeering.StatusName`
   * @link http://unknown-url
   */
  public readonly attrStatusName: string;
  /**
   * Attribute `MongoDB::Atlas::NetworkPeering.ErrorStateName`
   * @link http://unknown-url
   */
  public readonly attrErrorStateName: string;

  /**
   * Create a new `MongoDB::Atlas::NetworkPeering`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: cdk.Construct, id: string, props: CfnNetworkpeeringProps) {
    super(scope, id, { type: CfnNetworkpeering.CFN_RESOURCE_TYPE_NAME, properties: toJson_CfnNetworkpeeringProps(props)! });

    this.projectId = props.projectId;
    this.containerId = props.containerId;
    this.accepterRegionName = props.accepterRegionName;
    this.awsAccountId = props.awsAccountId;
    this.providerName = props.providerName;
    this.routeTableCIDRBlock = props.routeTableCIDRBlock;
    this.vpcId = props.vpcId;
    this.connectionId = props.connectionId;
    this.apiKeys = props.apiKeys;
    this.attrId = cdk.Token.asString(this.getAtt('Id'));
    this.attrStatusName = cdk.Token.asString(this.getAtt('StatusName'));
    this.attrErrorStateName = cdk.Token.asString(this.getAtt('ErrorStateName'));
  }
}