// Generated by cdk-import
import * as cdk from 'aws-cdk-lib';
import * as constructs from 'constructs';

/**
 * Manage a Fastly service.
 *
 * @schema CfnServiceProps
 */
export interface CfnServiceProps {
  /**
   * @schema CfnServiceProps#Name
   */
  readonly name: string;

  /**
   * @schema CfnServiceProps#Comment
   */
  readonly comment?: string;

  /**
   * @schema CfnServiceProps#Paused
   */
  readonly paused?: boolean;

  /**
   * @schema CfnServiceProps#Id
   */
  readonly id?: string;

  /**
   * @schema CfnServiceProps#Type
   */
  readonly type?: Type;

  /**
   * @schema CfnServiceProps#CustomerId
   */
  readonly customerId?: string;

  /**
   * @schema CfnServiceProps#CreatedAt
   */
  readonly createdAt?: Date;

  /**
   * @schema CfnServiceProps#UpdatedAt
   */
  readonly updatedAt?: Date;

  /**
   * @schema CfnServiceProps#DeletedAt
   */
  readonly deletedAt?: Date;
}

/**
 * Converts an object of type 'CfnServiceProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CfnServiceProps(obj: CfnServiceProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Name': obj.name,
    'Comment': obj.comment,
    'Paused': obj.paused,
    'Id': obj.id,
    'Type': obj.type,
    'CustomerId': obj.customerId,
    'CreatedAt': obj.createdAt?.toISOString(),
    'UpdatedAt': obj.updatedAt?.toISOString(),
    'DeletedAt': obj.deletedAt?.toISOString(),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * The type of this service.
 *
 * @schema Type
 */
export enum Type {
  /** vcl */
  VCL = "vcl",
  /** wasm */
  WASM = "wasm",
}


/**
 * A CloudFormation `Fastly::Services::Service`
 *
 * @cloudformationResource Fastly::Services::Service
 * @stability external
 * @link https://github.com/aws-ia/cloudformation-fastly-resource-providers.git
 */
export class CfnService extends cdk.CfnResource {
  /**
  * The CloudFormation resource type name for this resource class.
  */
  public static readonly CFN_RESOURCE_TYPE_NAME = "Fastly::Services::Service";

  /**
   * Resource props.
   */
  public readonly props: CfnServiceProps;

  /**
   * Attribute `Fastly::Services::Service.ActiveVersionId`
   * @link https://github.com/aws-ia/cloudformation-fastly-resource-providers.git
   */
  public readonly attrActiveVersionId: number;
  /**
   * Attribute `Fastly::Services::Service.LatestVersionId`
   * @link https://github.com/aws-ia/cloudformation-fastly-resource-providers.git
   */
  public readonly attrLatestVersionId: number;

  /**
   * Create a new `Fastly::Services::Service`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: constructs.Construct, id: string, props: CfnServiceProps) {
    super(scope, id, { type: CfnService.CFN_RESOURCE_TYPE_NAME, properties: toJson_CfnServiceProps(props)! });

    this.props = props;

    this.attrActiveVersionId = cdk.Token.asNumber(this.getAtt('ActiveVersionId'));
    this.attrLatestVersionId = cdk.Token.asNumber(this.getAtt('LatestVersionId'));
  }
}