// Generated by cdk-import
import * as cdk from '@aws-cdk/core';

/**
 * Use the `akamai_dns_record` resource to configure a DNS record that can integrate with your existing DNS infrastructure.
 *
 * @schema CfnDnsrecordProps
 */
export interface CfnDnsrecordProps {
  /**
   * @schema CfnDnsrecordProps#Active
   */
  readonly active?: boolean;

  /**
   * @schema CfnDnsrecordProps#Algorithm
   */
  readonly algorithm?: number;

  /**
   * @schema CfnDnsrecordProps#Certificate
   */
  readonly certificate?: string;

  /**
   * @schema CfnDnsrecordProps#Digest
   */
  readonly digest?: string;

  /**
   * @schema CfnDnsrecordProps#DigestType
   */
  readonly digestType?: number;

  /**
   * @schema CfnDnsrecordProps#EmailAddress
   */
  readonly emailAddress?: string;

  /**
   * @schema CfnDnsrecordProps#Expiration
   */
  readonly expiration?: string;

  /**
   * @schema CfnDnsrecordProps#Expiry
   */
  readonly expiry?: number;

  /**
   * @schema CfnDnsrecordProps#Fingerprint
   */
  readonly fingerprint?: string;

  /**
   * @schema CfnDnsrecordProps#FingerprintType
   */
  readonly fingerprintType?: number;

  /**
   * @schema CfnDnsrecordProps#Flags
   */
  readonly flags?: number;

  /**
   * @schema CfnDnsrecordProps#Flagsnaptr
   */
  readonly flagsnaptr?: string;

  /**
   * @schema CfnDnsrecordProps#Hardware
   */
  readonly hardware?: string;

  /**
   * @schema CfnDnsrecordProps#Inception
   */
  readonly inception?: string;

  /**
   * @schema CfnDnsrecordProps#Iterations
   */
  readonly iterations?: number;

  /**
   * @schema CfnDnsrecordProps#Key
   */
  readonly key?: string;

  /**
   * @schema CfnDnsrecordProps#Keytag
   */
  readonly keytag?: number;

  /**
   * @schema CfnDnsrecordProps#Labels
   */
  readonly labels?: number;

  /**
   * @schema CfnDnsrecordProps#Mailbox
   */
  readonly mailbox?: string;

  /**
   * @schema CfnDnsrecordProps#MatchType
   */
  readonly matchType?: number;

  /**
   * @schema CfnDnsrecordProps#Name
   */
  readonly name: string;

  /**
   * @schema CfnDnsrecordProps#NameServer
   */
  readonly nameServer?: string;

  /**
   * @schema CfnDnsrecordProps#NextHashedOwnerName
   */
  readonly nextHashedOwnerName?: string;

  /**
   * @schema CfnDnsrecordProps#NxdomainTtl
   */
  readonly nxdomainTtl?: number;

  /**
   * @schema CfnDnsrecordProps#Order
   */
  readonly order?: number;

  /**
   * @schema CfnDnsrecordProps#OriginalTtl
   */
  readonly originalTtl?: number;

  /**
   * @schema CfnDnsrecordProps#Port
   */
  readonly port?: number;

  /**
   * @schema CfnDnsrecordProps#Preference
   */
  readonly preference?: number;

  /**
   * @schema CfnDnsrecordProps#Priority
   */
  readonly priority?: number;

  /**
   * @schema CfnDnsrecordProps#PriorityIncrement
   */
  readonly priorityIncrement?: number;

  /**
   * @schema CfnDnsrecordProps#Protocol
   */
  readonly protocol?: number;

  /**
   * @schema CfnDnsrecordProps#Recordtype
   */
  readonly recordtype: string;

  /**
   * @schema CfnDnsrecordProps#Refresh
   */
  readonly refresh?: number;

  /**
   * @schema CfnDnsrecordProps#Regexp
   */
  readonly regexp?: string;

  /**
   * @schema CfnDnsrecordProps#Replacement
   */
  readonly replacement?: string;

  /**
   * @schema CfnDnsrecordProps#Retry
   */
  readonly retry?: number;

  /**
   * @schema CfnDnsrecordProps#Salt
   */
  readonly salt?: string;

  /**
   * @schema CfnDnsrecordProps#Selector
   */
  readonly selector?: number;

  /**
   * @schema CfnDnsrecordProps#Service
   */
  readonly service?: string;

  /**
   * @schema CfnDnsrecordProps#Signature
   */
  readonly signature?: string;

  /**
   * @schema CfnDnsrecordProps#Signer
   */
  readonly signer?: string;

  /**
   * @schema CfnDnsrecordProps#Software
   */
  readonly software?: string;

  /**
   * @schema CfnDnsrecordProps#Subtype
   */
  readonly subtype?: number;

  /**
   * @schema CfnDnsrecordProps#SvcParams
   */
  readonly svcParams?: string;

  /**
   * @schema CfnDnsrecordProps#SvcPriority
   */
  readonly svcPriority?: number;

  /**
   * @schema CfnDnsrecordProps#Target
   */
  readonly target?: string[];

  /**
   * @schema CfnDnsrecordProps#TargetName
   */
  readonly targetName?: string;

  /**
   * @schema CfnDnsrecordProps#Ttl
   */
  readonly ttl: number;

  /**
   * @schema CfnDnsrecordProps#Txt
   */
  readonly txt?: string;

  /**
   * @schema CfnDnsrecordProps#TypeBitmaps
   */
  readonly typeBitmaps?: string;

  /**
   * @schema CfnDnsrecordProps#TypeCovered
   */
  readonly typeCovered?: string;

  /**
   * @schema CfnDnsrecordProps#TypeMnemonic
   */
  readonly typeMnemonic?: string;

  /**
   * @schema CfnDnsrecordProps#TypeValue
   */
  readonly typeValue?: number;

  /**
   * @schema CfnDnsrecordProps#Usage
   */
  readonly usage?: number;

  /**
   * @schema CfnDnsrecordProps#Weight
   */
  readonly weight?: number;

  /**
   * @schema CfnDnsrecordProps#Zone
   */
  readonly zone: string;

}

/**
 * Converts an object of type 'CfnDnsrecordProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnDnsrecordProps(obj: CfnDnsrecordProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'Active': obj.active,
    'Algorithm': obj.algorithm,
    'Certificate': obj.certificate,
    'Digest': obj.digest,
    'DigestType': obj.digestType,
    'EmailAddress': obj.emailAddress,
    'Expiration': obj.expiration,
    'Expiry': obj.expiry,
    'Fingerprint': obj.fingerprint,
    'FingerprintType': obj.fingerprintType,
    'Flags': obj.flags,
    'Flagsnaptr': obj.flagsnaptr,
    'Hardware': obj.hardware,
    'Inception': obj.inception,
    'Iterations': obj.iterations,
    'Key': obj.key,
    'Keytag': obj.keytag,
    'Labels': obj.labels,
    'Mailbox': obj.mailbox,
    'MatchType': obj.matchType,
    'Name': obj.name,
    'NameServer': obj.nameServer,
    'NextHashedOwnerName': obj.nextHashedOwnerName,
    'NxdomainTtl': obj.nxdomainTtl,
    'Order': obj.order,
    'OriginalTtl': obj.originalTtl,
    'Port': obj.port,
    'Preference': obj.preference,
    'Priority': obj.priority,
    'PriorityIncrement': obj.priorityIncrement,
    'Protocol': obj.protocol,
    'Recordtype': obj.recordtype,
    'Refresh': obj.refresh,
    'Regexp': obj.regexp,
    'Replacement': obj.replacement,
    'Retry': obj.retry,
    'Salt': obj.salt,
    'Selector': obj.selector,
    'Service': obj.service,
    'Signature': obj.signature,
    'Signer': obj.signer,
    'Software': obj.software,
    'Subtype': obj.subtype,
    'SvcParams': obj.svcParams,
    'SvcPriority': obj.svcPriority,
    'Target': obj.target?.map(y => y),
    'TargetName': obj.targetName,
    'Ttl': obj.ttl,
    'Txt': obj.txt,
    'TypeBitmaps': obj.typeBitmaps,
    'TypeCovered': obj.typeCovered,
    'TypeMnemonic': obj.typeMnemonic,
    'TypeValue': obj.typeValue,
    'Usage': obj.usage,
    'Weight': obj.weight,
    'Zone': obj.zone,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 * A CloudFormation `TF::Akamai::DnsRecord`
 *
 * @cloudformationResource TF::Akamai::DnsRecord
 * @stability external
 * @link https://github.com/iann0036/cfn-tf-custom-types.git
 */
export class CfnDnsrecord extends cdk.CfnResource {
  /**
  * The CloudFormation resource type name for this resource class.
  */
  public static readonly CFN_RESOURCE_TYPE_NAME = "TF::Akamai::DnsRecord";

  /**
   * `TF::Akamai::DnsRecord.Active`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly active: any | undefined;
  /**
   * `TF::Akamai::DnsRecord.Algorithm`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly algorithm: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Certificate`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly certificate: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Digest`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly digest: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.DigestType`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly digestType: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.EmailAddress`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly emailAddress: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Expiration`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly expiration: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Expiry`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly expiry: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Fingerprint`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly fingerprint: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.FingerprintType`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly fingerprintType: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Flags`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly flags: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Flagsnaptr`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly flagsnaptr: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Hardware`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly hardware: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Inception`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly inception: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Iterations`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly iterations: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Key`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly key: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Keytag`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly keytag: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Labels`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly labels: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Mailbox`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly mailbox: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.MatchType`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly matchType: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Name`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly name: string;
  /**
   * `TF::Akamai::DnsRecord.NameServer`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly nameServer: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.NextHashedOwnerName`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly nextHashedOwnerName: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.NxdomainTtl`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly nxdomainTtl: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Order`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly order: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.OriginalTtl`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly originalTtl: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Port`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly port: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Preference`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly preference: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Priority`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly priority: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.PriorityIncrement`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly priorityIncrement: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Protocol`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly protocol: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Recordtype`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly recordtype: string;
  /**
   * `TF::Akamai::DnsRecord.Refresh`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly refresh: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Regexp`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly regexp: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Replacement`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly replacement: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Retry`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly retry: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Salt`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly salt: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Selector`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly selector: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Service`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly service: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Signature`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly signature: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Signer`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly signer: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Software`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly software: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Subtype`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly subtype: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.SvcParams`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly svcParams: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.SvcPriority`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly svcPriority: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Target`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly target: string[] | undefined;
  /**
   * `TF::Akamai::DnsRecord.TargetName`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly targetName: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.Ttl`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly ttl: number;
  /**
   * `TF::Akamai::DnsRecord.Txt`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly txt: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.TypeBitmaps`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly typeBitmaps: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.TypeCovered`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly typeCovered: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.TypeMnemonic`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly typeMnemonic: string | undefined;
  /**
   * `TF::Akamai::DnsRecord.TypeValue`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly typeValue: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Usage`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly usage: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Weight`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly weight: number | undefined;
  /**
   * `TF::Akamai::DnsRecord.Zone`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly zone: string;
  /**
   * Attribute `TF::Akamai::DnsRecord.tfcfnid`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly attrTfcfnid: string;
  /**
   * Attribute `TF::Akamai::DnsRecord.AnswerType`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly attrAnswerType: string;
  /**
   * Attribute `TF::Akamai::DnsRecord.DnsName`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly attrDnsName: string;
  /**
   * Attribute `TF::Akamai::DnsRecord.Id`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly attrId: string;
  /**
   * Attribute `TF::Akamai::DnsRecord.RecordSha`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly attrRecordSha: string;
  /**
   * Attribute `TF::Akamai::DnsRecord.Serial`
   * @link https://github.com/iann0036/cfn-tf-custom-types.git
   */
  public readonly attrSerial: number;

  /**
   * Create a new `TF::Akamai::DnsRecord`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: cdk.Construct, id: string, props: CfnDnsrecordProps) {
    super(scope, id, { type: CfnDnsrecord.CFN_RESOURCE_TYPE_NAME, properties: toJson_CfnDnsrecordProps(props)! });

    this.active = props.active;
    this.algorithm = props.algorithm;
    this.certificate = props.certificate;
    this.digest = props.digest;
    this.digestType = props.digestType;
    this.emailAddress = props.emailAddress;
    this.expiration = props.expiration;
    this.expiry = props.expiry;
    this.fingerprint = props.fingerprint;
    this.fingerprintType = props.fingerprintType;
    this.flags = props.flags;
    this.flagsnaptr = props.flagsnaptr;
    this.hardware = props.hardware;
    this.inception = props.inception;
    this.iterations = props.iterations;
    this.key = props.key;
    this.keytag = props.keytag;
    this.labels = props.labels;
    this.mailbox = props.mailbox;
    this.matchType = props.matchType;
    this.name = props.name;
    this.nameServer = props.nameServer;
    this.nextHashedOwnerName = props.nextHashedOwnerName;
    this.nxdomainTtl = props.nxdomainTtl;
    this.order = props.order;
    this.originalTtl = props.originalTtl;
    this.port = props.port;
    this.preference = props.preference;
    this.priority = props.priority;
    this.priorityIncrement = props.priorityIncrement;
    this.protocol = props.protocol;
    this.recordtype = props.recordtype;
    this.refresh = props.refresh;
    this.regexp = props.regexp;
    this.replacement = props.replacement;
    this.retry = props.retry;
    this.salt = props.salt;
    this.selector = props.selector;
    this.service = props.service;
    this.signature = props.signature;
    this.signer = props.signer;
    this.software = props.software;
    this.subtype = props.subtype;
    this.svcParams = props.svcParams;
    this.svcPriority = props.svcPriority;
    this.target = props.target;
    this.targetName = props.targetName;
    this.ttl = props.ttl;
    this.txt = props.txt;
    this.typeBitmaps = props.typeBitmaps;
    this.typeCovered = props.typeCovered;
    this.typeMnemonic = props.typeMnemonic;
    this.typeValue = props.typeValue;
    this.usage = props.usage;
    this.weight = props.weight;
    this.zone = props.zone;
    this.attrTfcfnid = cdk.Token.asString(this.getAtt('tfcfnid'));
    this.attrAnswerType = cdk.Token.asString(this.getAtt('AnswerType'));
    this.attrDnsName = cdk.Token.asString(this.getAtt('DnsName'));
    this.attrId = cdk.Token.asString(this.getAtt('Id'));
    this.attrRecordSha = cdk.Token.asString(this.getAtt('RecordSha'));
    this.attrSerial = cdk.Token.asNumber(this.getAtt('Serial'));
  }
}