// Generated by cdk-import
import * as cdk from 'aws-cdk-lib';
import * as constructs from 'constructs';

/**
 * Manage a Fastly service active version.
 *
 * @schema CfnActiveVersionProps
 */
export interface CfnActiveVersionProps {
  /**
   * Alphanumeric string identifying the service. Read-only.
   *
   * @schema CfnActiveVersionProps#ServiceId
   */
  readonly serviceId: string;

  /**
   * The number of the version to be activated.
   *
   * @schema CfnActiveVersionProps#VersionNumber
   */
  readonly versionNumber: number;

}

/**
 * Converts an object of type 'CfnActiveVersionProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnActiveVersionProps(obj: CfnActiveVersionProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ServiceId': obj.serviceId,
    'VersionNumber': obj.versionNumber,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


/**
 * A CloudFormation `Fastly::Services::ActiveVersion`
 *
 * @cloudformationResource Fastly::Services::ActiveVersion
 * @stability external
 * @link https://github.com/aws-ia/cloudformation-fastly-resource-providers.git
 */
export class CfnActiveVersion extends cdk.CfnResource {
  /**
  * The CloudFormation resource type name for this resource class.
  */
  public static readonly CFN_RESOURCE_TYPE_NAME = "Fastly::Services::ActiveVersion";

  /**
   * Resource props.
   */
  public readonly props: CfnActiveVersionProps;


  /**
   * Create a new `Fastly::Services::ActiveVersion`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: constructs.Construct, id: string, props: CfnActiveVersionProps) {
    super(scope, id, { type: CfnActiveVersion.CFN_RESOURCE_TYPE_NAME, properties: toJson_CfnActiveVersionProps(props)! });

    this.props = props;

  }
}