// Generated by cdk-import
import * as cdk from 'aws-cdk-lib';
import * as constructs from 'constructs';

/**
 * CRUD operations for New Relic Workloads via the NerdGraph API
 *
 * @schema CfnWorkloadsProps
 */
export interface CfnWorkloadsProps {
  /**
   * @schema CfnWorkloadsProps#SourceGuid
   */
  readonly sourceGuid?: string;

  /**
   * @schema CfnWorkloadsProps#DuplicateName
   */
  readonly duplicateName?: string;

  /**
   * @schema CfnWorkloadsProps#Workload
   */
  readonly workload?: string;

  /**
   * @schema CfnWorkloadsProps#ListQueryFilter
   */
  readonly listQueryFilter?: string;

  /**
   * @schema CfnWorkloadsProps#Variables
   */
  readonly variables?: any;

}

/**
 * Converts an object of type 'CfnWorkloadsProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CfnWorkloadsProps(obj: CfnWorkloadsProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'SourceGuid': obj.sourceGuid,
    'DuplicateName': obj.duplicateName,
    'Workload': obj.workload,
    'ListQueryFilter': obj.listQueryFilter,
    'Variables': obj.variables,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */


/**
 * A CloudFormation `NewRelic::CloudFormation::Workloads`
 *
 * @cloudformationResource NewRelic::CloudFormation::Workloads
 * @stability external
 * @link https://github.com/newrelic-experimental/newrelic-cloudformation-resource-providers-workloads.git
 */
export class CfnWorkloads extends cdk.CfnResource {
  /**
  * The CloudFormation resource type name for this resource class.
  */
  public static readonly CFN_RESOURCE_TYPE_NAME = "NewRelic::CloudFormation::Workloads";

  /**
   * Resource props.
   */
  public readonly props: CfnWorkloadsProps;

  /**
   * Attribute `NewRelic::CloudFormation::Workloads.Guid`
   * @link https://github.com/newrelic-experimental/newrelic-cloudformation-resource-providers-workloads.git
   */
  public readonly attrGuid: string;

  /**
   * Create a new `NewRelic::CloudFormation::Workloads`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: constructs.Construct, id: string, props: CfnWorkloadsProps) {
    super(scope, id, { type: CfnWorkloads.CFN_RESOURCE_TYPE_NAME, properties: toJson_CfnWorkloadsProps(props)! });

    this.props = props;

    this.attrGuid = cdk.Token.asString(this.getAtt('Guid'));
  }
}